In [12]:
#importing required libraries
from keras.preprocessing import image
from keras.models import load_model
import numpy as np
from google.colab import files

#uploading the model
print("Upload your model.h5 file:")
uploaded_model = files.upload()

#uploading testing files
print("Upload your image files:")
uploaded_images = files.upload()

#loading the model
model = load_model('model.h5')
print("Model Loaded Successfully")

#defining the classify function
def classify(img_file):
    test_image = image.load_img(img_file, target_size=(256, 256), color_mode='grayscale')
    test_image = image.img_to_array(test_image)
    test_image = np.expand_dims(test_image, axis=0)
    result = model.predict(test_image)
    arr = np.array(result[0])
    print(arr)
    max_prob = arr.argmax()
    classes = ["NONE", "ONE", "TWO", "THREE", "FOUR", "FIVE"]
    prediction = classes[max_prob]
    print(img_file, prediction)

#printing all the classified functions
for img_file in uploaded_images.keys():
    classify(img_file)
    print('\n')


Upload your model.h5 file:


Saving model.h5 to model.h5
Upload your image files:


Saving FIVE_564.png to FIVE_564.png
Saving FIVE_565.png to FIVE_565.png
Saving FIVE_566.png to FIVE_566.png
Saving FIVE_567.png to FIVE_567.png
Saving FOUR_600.png to FOUR_600.png
Saving FOUR_601.png to FOUR_601.png
Saving FOUR_602.png to FOUR_602.png
Saving FOUR_603.png to FOUR_603.png
Saving THREE_592.png to THREE_592.png
Saving THREE_593.png to THREE_593.png
Saving THREE_594.png to THREE_594.png
Saving THREE_595.png to THREE_595.png
Saving TWO_601.png to TWO_601.png
Saving TWO_602.png to TWO_602.png
Saving TWO_603.png to TWO_603.png
Saving TWO_604.png to TWO_604.png
Saving ONE_604.png to ONE_604.png
Saving ONE_592.png to ONE_592.png
Saving ONE_593.png to ONE_593.png
Saving ONE_594.png to ONE_594.png
Saving NONE_604.png to NONE_604.png
Saving NONE_605.png to NONE_605.png
Saving NONE_606.png to NONE_606.png
Saving NONE_591.png to NONE_591.png


Model Loaded Successfully
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step
[0.0000000e+00 0.0000000e+00 0.0000000e+00 9.9999702e-01 2.9236471e-06
 0.0000000e+00]
FIVE_564.png THREE


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step
[0.0000000e+00 0.0000000e+00 0.0000000e+00 7.0892674e-26 1.0000000e+00
 0.0000000e+00]
FIVE_565.png FOUR


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step
[0.0000000e+00 0.0000000e+00 0.0000000e+00 1.2680314e-21 1.0000000e+00
 0.0000000e+00]
FIVE_566.png FOUR


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step
[0. 0. 0. 0. 1. 0.]
FIVE_567.png FOUR


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step
[0. 0. 0. 1. 0. 0.]
FOUR_600.png THREE


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step
[0. 0. 0. 1. 0. 0.]
FOUR_601.png THREE


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step
[0. 0. 0. 1. 0. 0.]
FOUR_602.png THREE


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step
[0. 0. 0. 1. 0. 0.]
FOUR_603.png THREE


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step
[0.0000000e+00 0.0000000e+00 3.3717253e-28 1.0000000e+00 0.0000000e+00
 0.0000000e+00]
THREE_592.png T